service: serverless-test
frameworkVersion: "3"
useDotenv: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    ACCESS_KEY_Id: ${env:ACCESS_KEY_Id}
    SECRET_ACCESS_KEY: ${env:SECRET_ACCESS_KEY}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
        - dynamodb:*
      Resource:
        { "Fn::Join": ["", ["arn:aws:s3:::serverless-test-urana", "/*"]] }
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:198585734565:table/PersonTable

functions:
  api:
    handler: handler.api
    events:
      - httpApi:
          path: "/api/v1/{section}/{id+}"
          method: "*"
